# .github/workflows/dependabot_automerge.yml
# Workflow to automatically approve and enable auto-merge for Dependabot patch updates.
# Adapted from https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enabling-automerge-on-a-pull-request

name: Dependabot auto-merge
on: pull_request_target # Use pull_request_target for security best practices with GITHUB_TOKEN

permissions:
  contents: write       # Needed to write merge commits
  pull-requests: write  # Needed to approve and merge PRs

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Check if the PR is from Dependabot and in the correct repository
    if: github.actor == 'dependabot[bot]' && github.repository == 'cryvii/toqito'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0 # Use a specific version
        with:
          # GITHUB_TOKEN is automatically available with pull_request_target
          github-token: "${{ secrets.GITHUB_TOKEN }}" 

      # Approve and enable auto-merge for Dependabot patch updates
      - name: Enable auto-merge for Dependabot patch updates
        # Check if the update type is a patch update
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}} # Pass token explicitly to gh cli
