"""Test pauli channel."""

import re

import numpy as np
import pytest
from scipy.linalg import eigvalsh

from toqito.channel_ops import apply_channel
from toqito.channels import pauli_channel
from toqito.matrix_ops import partial_trace


@pytest.mark.parametrize(
    "in_p",
    [
        # Negative probability.
        ([-0.1, 1.1]),
        # Incorrect length.
        ([0.2, 0.2, 0.2, 0.2, 0.2]),
        # Out of range probabilities.
        ([1.1, 0.1]),
    ],
)
def test_pauli_channel_valid_probability(in_p):
    """Test probability vector validation with various invalid inputs."""
    with pytest.raises(
        ValueError,
        match=(
            re.escape("Probabilities must be non-negative and sum to 1.")
            + "|"
            + re.escape("The length of the probability vector must be 4^q for some integer q (number of qubits).")
        ),
    ):
        pauli_channel(prob=in_p)


@pytest.mark.parametrize(
    "num_qubits,expected_dim",
    [
        # Single qubit.
        (1, 4),
        # Two qubits.
        (2, 16),
        # Three qubits.
        (3, 64),
    ],
)
def test_pauli_channel_dimensions(num_qubits, expected_dim):
    """Test Pauli channel generation for different numbers of qubits."""
    p = np.ones(expected_dim) / expected_dim
    Phi = pauli_channel(prob=p)
    assert Phi.shape == (expected_dim, expected_dim)


@pytest.mark.parametrize(
    "input_mat, prob",
    [
        # Identity matrix.
        (np.eye(2), np.array([0.1, 0.2, 0.3, 0.4])),
        # Pure state.
        (np.array([[1, 0], [0, 0]], dtype=complex), np.array([0.25, 0.25, 0.25, 0.25])),
    ],
)
def test_pauli_channel_output_matrix_properties(input_mat, prob):
    """Output of `apply_channel` on a Pauli channel is Hermitian, PSD, and trace-preserving."""
    prob = prob / np.sum(prob)
    output_mat = apply_channel(input_mat, pauli_channel(prob=prob))

    assert np.allclose(output_mat, output_mat.conj().T)

    eig_v = eigvalsh(output_mat)
    assert np.all(eig_v >= -1e-10)

    assert np.isclose(np.trace(output_mat), np.trace(input_mat))


@pytest.mark.parametrize("num_qubits", [1, 2, 3])
def test_pauli_channel_choi_matrix_properties(num_qubits):
    """Test Choi matrix properties for different numbers of qubits.

    Verifies the following properties of the Choi matrix generated by the Pauli channel:

    - The Choi matrix has the expected dimension `(4**q, 4**q)`.
    - It is positive semidefinite.
    - Its partial trace over the output system yields the identity matrix of the input Hilbert space.
    - Its total trace equals the input dimension `(2**q)`.

    """
    Phi = pauli_channel(prob=num_qubits)
    Phi = np.array(Phi)
    expected_choi_dim = 4**num_qubits
    assert Phi.shape == (expected_choi_dim, expected_choi_dim)

    eigenvalues = eigvalsh(Phi)
    assert np.all(eigenvalues >= -1e-10)

    input_dim = 2**num_qubits
    dims = [input_dim, input_dim]
    pt_output = partial_trace(Phi, sys=1, dim=dims)
    identity_input = np.eye(input_dim)
    assert np.allclose(pt_output, identity_input)

    total_trace = np.trace(Phi)
    assert np.isclose(total_trace, input_dim)


@pytest.mark.parametrize("prob", [np.array([0.1, 0.2, 0.3, 0.4]), np.random.rand(16)])
def test_pauli_channel_kraus_operators_legacy(prob):
    """The deprecated `return_kraus_ops=True` path still returns valid Kraus operators."""
    prob = prob / np.sum(prob)
    with pytest.warns(DeprecationWarning, match="choi_to_kraus"):
        _, kraus_operators = pauli_channel(prob=prob, return_kraus_ops=True)

    assert len(kraus_operators) == len(prob)

    total_ops = np.zeros_like(kraus_operators[0], dtype=np.complex128)
    for K in kraus_operators:
        total_ops += K.conj().T @ K

    np.testing.assert_almost_equal(total_ops, np.eye(total_ops.shape[0]), decimal=10)


@pytest.mark.parametrize(
    "prob",
    [
        # Multiple 0 entries.
        np.array([0.0, 0.5, 0.0, 0.5]),
        # Single 0 entries.
        np.array([0.25, 0.0, 0.25, 0.5]),
    ],
)
def test_pauli_channel_zero_probability_legacy(prob):
    """Deprecated path: when probabilities are zero, the per-index Kraus operator is zero."""
    with pytest.warns(DeprecationWarning, match="choi_to_kraus"):
        _, kraus_ops = pauli_channel(prob=prob, return_kraus_ops=True)

    for i, k in enumerate(kraus_ops):
        if prob[i] == 0:
            np.testing.assert_almost_equal(k, np.zeros_like(k))


def test_pauli_channel_input_mat_is_deprecated():
    """Passing `input_mat` still works but emits a DeprecationWarning."""
    prob = np.array([0.1, 0.2, 0.3, 0.4])
    input_mat = np.eye(2)
    with pytest.warns(DeprecationWarning, match="apply_channel"):
        _, legacy = pauli_channel(prob=prob, input_mat=input_mat)
    modern = apply_channel(input_mat, pauli_channel(prob=prob))
    np.testing.assert_almost_equal(legacy, np.asarray(modern))


def test_pauli_channel_return_kraus_ops_is_deprecated():
    """Passing `return_kraus_ops=True` still works but emits a DeprecationWarning."""
    prob = np.array([0.25, 0.25, 0.25, 0.25])
    with pytest.warns(DeprecationWarning, match="choi_to_kraus"):
        result = pauli_channel(prob=prob, return_kraus_ops=True)
    assert len(result) == 2
