"""Generates the Choi matrix of a Pauli channel."""

import itertools
import warnings

import numpy as np
from scipy import sparse

from toqito.channel_ops.kraus_to_choi import kraus_to_choi
from toqito.matrices.pauli import pauli


def pauli_channel(
    prob: int | np.ndarray, return_kraus_ops: bool = False, input_mat: np.ndarray | None = None
) -> np.ndarray | sparse.csc_matrix | tuple:
    r"""Return the Choi matrix of a Pauli channel.

    The Pauli channel is defined by a set of Pauli operators weighted by a probability vector.
    For a given probability vector \((p_0, \ldots, p_{4^q -1 })\), the channel is defined as
    shown below. Where, $q$ is the number of qubits.

    \[
        \Phi(\rho) = \sum_{i=0}^{4^q - 1} p_i P_i \rho P_i^*
    \]

    where \(P_i\) are Pauli operators generated by a lexicographically increasing sequence of pauli operators of
    length strictly equal to \(q\), and \(p_i\) is the corresponding probability of that operator.
    For example, when \(q = 2\),

    \(P_{0} = I \otimes I\), \(P_{1} = I \otimes X\), \(P_{2} = I \otimes Y\), \(P_{3} = I \otimes Z\),
    \(P_{4} = X \otimes I\), \(P_{5} = X \otimes Y , \ldots P_{15} = Z \otimes Z\)

    If `prob` is a scalar, it generates a random `prob`-qubit Pauli channel.
    The length of the probability vector (if provided) must be \(4^q\) for some
    integer \(q\) (number of qubits).

    Args:
        prob: Probability vector for Pauli operators. If scalar, generates random probabilities for \(q =\) `prob`
            qubits. The probabilities correspond to Pauli operators in lexicographical order of length strictly equal to
            \(q\), when `prob` is a vector.
        return_kraus_ops: Deprecated. When ``True``, the Kraus operators are returned in a
            tuple alongside the Choi matrix. Prefer
            `choi_to_kraus(pauli_channel(...))` to obtain Kraus operators.
        input_mat: Deprecated. When provided, the channel is also applied to this matrix and
            returned in a tuple alongside the Choi matrix. Prefer
            `apply_channel(input_mat, pauli_channel(...))` instead.

    Returns:
        The Choi matrix of the Pauli channel as a sparse matrix. When the deprecated
        ``input_mat`` / ``return_kraus_ops`` arguments are used, a tuple including the output
        matrix and/or Kraus operators is returned for backward compatibility.

    Raises:
        ValueError: If probabilities are negative or don't sum to 1.
        ValueError: If length of probability vector is not ``4^q`` for some integer ``q``.

    Examples:
        Generate the Choi matrix of a random single-qubit Pauli channel:

        ```python exec="1" source="above" result="text"
        from toqito.channels import pauli_channel

        print(pauli_channel(prob=1))
        ```

        Apply a specific two-qubit Pauli channel to an input matrix via `apply_channel`:

        ```python exec="1" source="above" result="text"
        import numpy as np
        from toqito.channels import pauli_channel
        from toqito.channel_ops import apply_channel

        choi = pauli_channel(prob=np.array([0.1, 0.2, 0.3, 0.4]))
        print(apply_channel(np.eye(2), choi))
        ```

    """
    if not isinstance(prob, np.ndarray):
        if np.isscalar(prob):
            q = prob
            prob = np.random.rand(4**q)
            prob /= np.sum(prob)
        else:
            prob = np.array(prob)

    if np.any(prob < 0) or not np.isclose(np.sum(prob), 1):
        raise ValueError("Probabilities must be non-negative and sum to 1.")

    q = int(np.round(np.log2(len(prob)) / 2))
    if len(prob) != 4**q:
        raise ValueError("The length of the probability vector must be 4^q for some integer q (number of qubits).")

    Phi = sparse.csc_matrix((4**q, 4**q), dtype=complex)

    kraus_operators = []

    for j, ind in enumerate(itertools.product(range(4), repeat=q)):
        pauli_op = pauli(list(ind))
        kraus_operators.append(np.sqrt(prob[j]) * pauli_op)
        Phi += prob[j] * kraus_to_choi([[pauli_op, pauli_op.conj().T]])

    if input_mat is not None:
        warnings.warn(
            "Passing `input_mat` to `pauli_channel` is deprecated; "
            "use `apply_channel(input_mat, pauli_channel(...))` instead.",
            DeprecationWarning,
            stacklevel=2,
        )
    if return_kraus_ops:
        warnings.warn(
            "The `return_kraus_ops` argument to `pauli_channel` is deprecated; "
            "use `choi_to_kraus(pauli_channel(...))` instead.",
            DeprecationWarning,
            stacklevel=2,
        )

    output_mat = None
    if input_mat is not None:
        output_mat = sum(k @ input_mat @ k.conj().T for k in kraus_operators)

    if return_kraus_ops:
        return (Phi, output_mat, kraus_operators) if input_mat is not None else (Phi, kraus_operators)

    return (Phi, output_mat) if input_mat is not None else Phi
