"""Properties of matrices and vectors."""
from toqito.matrix_props.has_same_dimension import has_same_dimension
from toqito.matrix_props.is_square import is_square
from toqito.matrix_props.kp_norm import kp_norm
from toqito.matrix_props.is_hermitian import is_hermitian
from toqito.matrix_props.is_positive_semidefinite import is_positive_semidefinite
from toqito.matrix_props.is_density import is_density
from toqito.matrix_props.is_circulant import is_circulant
from toqito.matrix_props.is_diagonal import is_diagonal
from toqito.matrix_props.is_normal import is_normal
from toqito.matrix_props.is_orthonormal import is_orthonormal
from toqito.matrix_props.is_symmetric import is_symmetric
from toqito.matrix_props.is_identity import is_identity
from toqito.matrix_props.is_idempotent import is_idempotent
from toqito.matrix_props.is_permutation import is_permutation
from toqito.matrix_props.is_positive_definite import is_positive_definite
from toqito.matrix_props.is_commuting import is_commuting
from toqito.matrix_props.is_projection import is_projection
from toqito.matrix_props.is_unitary import is_unitary
from toqito.matrix_props.majorizes import majorizes
from toqito.matrix_props.sk_norm import sk_operator_norm
from toqito.matrix_props.is_block_positive import is_block_positive
from toqito.matrix_props.trace_norm import trace_norm
from toqito.matrix_props.is_diagonally_dominant import is_diagonally_dominant
from toqito.matrix_props.is_totally_positive import is_totally_positive
from toqito.matrix_props.is_linearly_independent import is_linearly_independent
